version: '3.8'

services:
  user-services:
    build: ./user-services
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db_user  # Host cambiado
      - DB_PORT=5432
      - DB_NAME=${USER_DB_NAME}
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
    depends_on:
      - db_user

  map-services:
    build: ./map-services
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db_map  # Host cambiado
      - DB_PORT=5432
      - DB_NAME=${MAP_DB_NAME}
      - DB_USER=${MAP_DB_USER}
      - DB_PASSWORD=${MAP_DB_PASSWORD}
    depends_on:
      - db_map

  frontend-service:
    build: ./frontend-service
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=https://www.grupofuturo.com.ar/api  # URL actualizada

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - frontend-service
      - user-services
      - map-services

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

  db_user:  # Nombre cambiado
    image: postgres:13
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_map:  # Nombre cambiado
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: ${MAP_DB_NAME}
      POSTGRES_USER: ${MAP_DB_USER}
      POSTGRES_PASSWORD: ${MAP_DB_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgis_data: