
services:
  db:
    image: postgis/postgis:latest
    container_name: db_map
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  map-service:
    build: .
    container_name: map-service
    command: node src/app.js
    volumes:
      - .:/usr/src/app
      - uploads:/usr/src/app/uploads
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db_map
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads: