version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: map_db
    env_file:
      - .env  # ✅ Esto asegurará que se carguen las variables de entorno
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  map-service:
    build: .
    container_name: map-service
    command: node src/app.js
    volumes:
      - .:/usr/src/app
      - uploads:/usr/src/app/uploads
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  # ✅ Asegurar que las variables se cargan correctamente

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads:
