name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend-service
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" | tr -d '\r' > ~/.ssh/github-actions
        chmod 600 ~/.ssh/github-actions

    - name: Deploy to server
      env:
        SERVER_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        SERVER_USER: root
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker-compose up -d --no-deps frontend
        EOF
