name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    - name: Intentar conexión SSH manualmente
      run: |
        ssh -vvv -i ~/.ssh/github-actions -o StrictHostKeyChecking=no ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }} "echo 'SSH connection successful'"
    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
    - name: Verificar si la clave SSH se escribe correctamente
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" | tr -d '\r' > ~/.ssh/github-actions
        chmod 600 ~/.ssh/github-actions
        ls -la ~/.ssh
        cat ~/.ssh/github-actions | wc -l
    - name: Debug Secrets
      run: echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" | wc -l

    # 🔹 Configuración de la clave SSH
    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" | tr -d '\r' > ~/.ssh/github-actions
        chmod 600 ~/.ssh/github-actions
        ssh-keyscan -H ${{ secrets.DIGITALOCEAN_HOST }} >> ~/.ssh/known_hosts

    # 🔹 Prueba de conexión SSH antes del deploy
    - name: Debug SSH Connection
      run: |
        ssh -i ~/.ssh/github-actions ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }} "echo 'SSH connection successful'"

    # 🔹 Deploy al servidor
    - name: Deploy to server
      env:
        SERVER_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        SERVER_USER: ${{ secrets.DIGITALOCEAN_USERNAME }}
      run: |
        ssh -i ~/.ssh/github-actions $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /root/grupofuturo
          docker-compose pull
          docker-compose up -d --build
          docker system prune -f
        EOF
