version: '3.8'

services:
  frontend-service:
    build: .
    container_name: frontend-service
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=https://www.grupofuturo.com.ar/api
    volumes:
      - .:/usr/src/app
    command: npm start

networks:
  default:
    driver: bridge